### ISSUE TITLE
Issue with math

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/lora-raw#86]
```
Apr 16 02:52:58 raspberrypi lora-raw[1902]: 2021-04-16 02:52:58,254 DEBUG: src.lora.serial_connection_listener> Sensor payload: {'rssi': -208, 'snr': 0.0, 'pressure': 988.6, 'temperature': 25.06, 'humidity': 43, 'voltage': 4.78, 'light': 7, 'motion': False}
Apr 16 02:52:58 raspberrypi lora-raw[1902]: Exception in thread Thread-2:
Apr 16 02:52:58 raspberrypi lora-raw[1902]: Traceback (most recent call last):
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "threading.py", line 954, in _bootstrap_inner
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/background.py", line 24, in run
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "threading.py", line 892, in run
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/lora/serial_connection_listener.py", line 36, in start
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/lora/serial_connection_listener.py", line 70, in __start
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/lora/serial_connection_listener.py", line 114, in __read_serial_loop
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/lora/serial_connection_listener.py", line 146, in __decode_device
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/models/model_point.py", line 90, in update_point_value
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/models/model_point.py", line 123, in apply_value_operation
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/utils/math_functions.py", line 29, in eval_arithmetic_expression
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/utils/math_functions.py", line 36, in __eval
Apr 16 02:52:58 raspberrypi lora-raw[1902]:   File "src/utils/math_functions.py", line 38, in __eval
Apr 16 02:52:58 raspberrypi lora-raw[1902]: TypeError: <ast.UnaryOp object at 0x73f74e68>
Apr 16 02:53:00 raspberrypi lora-raw[1902]: 2021-04-16 02:53:00,970 INFO: gunicorn.access> 127.0.0.1 - - [16/Apr/2021:02:53:00 +0000] "GET /api/lora/devices HTTP/1.1" 200 19704 "-" "python-requests/2.25.1"
Apr 16 02:53:03 raspberrypi lora-raw[1902]: 2021-04-16 02:53:03,448 INFO: gunicorn.access> 127.0.0.1 - - [16/Apr/2021:02:53:03 +0000] "GET /api/lora/devices HTTP/1.1" 200 19704 "-" "python-requests/2.25.1"

````

**Comment by RaiBnod** [comment]
It was due to the decoder value boolean and the math operation: `x+0`.  Now, each decoder value is converted into numeric form (`0.0` for `False`, `1.0` for `True`) which will solve this issue.
